platform :ios, '9.1'
use_frameworks!

pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git', :branch => 'release-2.1'
pod 'Mixpanel'
pod 'Intercom'
pod 'Parse'
pod 'SwiftyJSON', '~> 2.3'
pod 'Charts', '2.2.3'